import React from 'react'
import { makeStyles } from "@material-ui/core/styles";
import CssBaseline from "@material-ui/core/CssBaseline";
import Typography from "@material-ui/core/Typography";
import IconButton from "@material-ui/core/IconButton";
import Paper from "@material-ui/core/Paper";
import List from "@material-ui/core/List";

import ListSubheader from "@material-ui/core/ListSubheader";
import Avatar from "@material-ui/core/Avatar";
import Card from '@material-ui/core/Card';
import CardHeader from '@material-ui/core/CardHeader';
import CardContent from '@material-ui/core/CardContent';
import CardActions from '@material-ui/core/CardActions';
import { red } from '@material-ui/core/colors';
import VisibilityOutlinedIcon from '@material-ui/icons/VisibilityOutlined';
import CommentIcon from "@material-ui/icons/Comment";

const messages = [
    {
      id: 1,
      primary: "Brunch this week?",
      secondary:
        "I'll be in the neighbourhood this week. Let's grab a bite to eat",
      person: "/static/images/avatar/5.jpg"
    },
    {
      id: 2,
      primary: "Birthday Gift",
      secondary: `Do you have a suggestion for a good present for John on his work
        anniversary. I am really confused & would love your thoughts on it.`,
      person: "/static/images/avatar/1.jpg"
    },
    {
      id: 3,
      primary: "Recipe to try",
      secondary:
        "I am try out this new BBQ recipe, I think this might be amazing",
      person: "/static/images/avatar/2.jpg"
    },
    {
      id: 4,
      primary: "Yes!",
      secondary: "I have the tickets to the ReactConf for this year.",
      person: "/static/images/avatar/3.jpg"
    },
    {
      id: 5,
      primary: "Doctor's Appointment",
      secondary:
        "My appointment for the doctor was rescheduled for next Saturday.",
      person: "/static/images/avatar/4.jpg"
    },
    {
      id: 6,
      primary: "Discussion",
      secondary: `Menus that are generated by the bottom app bar (such as a bottom
        navigation drawer or overflow menu) open as bottom sheets at a higher elevation
        than the bar.Who wants to have a cookout this weekend? I just got some furniture
        for my backyard and would love to fire up the grill. 
        chills and amanjoijghujhijijhgjfjhfgjjhWho wants to have a cookout this weekend? I just got some furniture
        for my backyard and would love to fire up the grill. 
        chills and amanjoijghujhijijhgjfjhfgjjh`,
      person: "/static/images/avatar/5.jpg"
    },
    {
      id: 7,
      primary: "Summer BBQ",
      secondary: `Who wants to have a cookout this weekend? I just got some furniture
        for my backyard and would love to fire up the grill. 
        chills and amanjoijghujhijijhgjfjhfgjjh`,
      person: "/static/images/avatar/1.jpg"
    }
  ];
  
  const useStyles = makeStyles(theme => ({
    text: {
      padding: theme.spacing(2, 2, 0)
    },
    paper: {
      paddingBottom: 50
    },
    list: {
      marginBottom: theme.spacing(2)
    },
    subheader: {
      backgroundColor: theme.palette.background.paper,
      marginBottom:20
    },
    appBar: {
      top: "auto",
      bottom: 0
    },
    card: {
      // flexGrow: 1,
      // display:'flex',
      marginBottom:20
      
    },
    expand: {
      marginLeft: 'auto',
  
   },
   avatar: {
     backgroundColor: red[500],
   },
  }));
function Posts() {
    const classes = useStyles();

    return (
      <React.Fragment>
        <CssBaseline />
        <Paper square className={classes.paper}>
          <Typography className={classes.text} variant="h5" gutterBottom>
            All Posts
          </Typography>
          <List className={classes.list}>
            {messages.map(({ id, primary, secondary, person }) => (
              <React.Fragment key={id}>
                {id === 1 && (
                  <ListSubheader className={classes.subheader}>
                    Today
                  </ListSubheader>
                )}
                {id === 3 && (
                  <ListSubheader className={classes.subheader}>
                    Yesterday
                  </ListSubheader>
                )}
               
               <Card className={classes.card} >
      <CardHeader
        avatar={
          <Avatar aria-label="recipe" className={classes.avatar}>
            R
          </Avatar>
        }
        // action={
        //   <IconButton aria-label="settings">
        //     <MoreVertIcon />
        //   </IconButton>
        // }
        title={primary}
        subheader="September 14, 2016"
      />
  
      <CardContent>
        <Typography variant="body2" color="textSecondary" component="p">
          {secondary}.
        </Typography>
      </CardContent>

      <CardActions disableSpacing>
        <IconButton aria-label="add to favorites">
          <VisibilityOutlinedIcon/>
        </IconButton>

        <IconButton 
          className={classes.expand}
        edge="end" aria-label="comments">
                    <CommentIcon />
        </IconButton>
      </CardActions>
  
    </Card>
              </React.Fragment>
            ))}
          </List>
        </Paper>
      </React.Fragment>
    );
}

export default Posts
